--1. 회원
CREATE TABLE AMEMBERS
(
    MID         CHAR(7)         NOT NULL PRIMARY KEY,
    MNAME       VARCHAR2(30)    NOT NULL
);

INSERT INTO MEMBERS VALUES('M000001','홍길동');
INSERT INTO MEMBERS VALUES('M000002','전우치');
INSERT INTO MEMBERS VALUES('M000003','박희은');
INSERT INTO MEMBERS VALUES('M000004','박효진');
INSERT INTO MEMBERS VALUES('M000005','김시영');

--COMMIT;
